### PR TITLE
doc updates

### PR DESCRIPTION
**Pull request by jtslear**

### CODE REVIEW

**Comment by homeyer** [comment]
this a temporary issue? 
image

**Comment by kellihsf** [comment]
I ran into that too on: help.waffle.io

**Comment by homeyer** [comment]
documentation link on takeout help page is wrong:

**Review by homeyer — COMMENTED** [review]
figure out https issue

**Comment by jtslear** [comment]
I'm not seeing the SSL issue.

**Comment by jtslear** [comment]
I've corrected the documentation link to the appropriate one.

**Review by kellihsf — APPROVED** [review]
Links checked, looks good

**Pull request merged**
